apps/loginReg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^dashboard$', views.dashboard, name = 'dashboard'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^addBook$', views.addBook, name = 'addBook'),
    url(r'^delete/(?P<author_id>\d*)$', views.delete),
    url(r'^wish_items/(?P<author_id>\d*)$', views.wish_items),
]

apps/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
]

login/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^main/', include('apps.loginReg.urls', namespace = "users")),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace = "wishlist")),
]

apps/books/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/loginReg/models.py
from __future__ import unicode_literals

from django.db import models
import re, bcrypt

class UserManager(models.Manager):
    def add_user(self, postData):
        errors = []
        if not len(postData['first_name']):
            errors.append('First name is required')
        if len(postData['first_name']) < 3:
            errors.append('Name must be at 3 characters long!')
        if len(postData['userName']) < 3:
            errors.append('User Name must be at 3 characters long!')
        if not len(postData['userName']):
            errors.append('userName is required!')
        check_email = self.filter(userName = postData['userName'])
        if check_email:
            errors.append('Sorry userName already exists!')
        if len(postData['password']) < 8:
            errors.append('Password must be at least 8 characters!')
        if not postData['password'] == postData['confirm_password']:
            errors.append('Passwords must match!')
        modelsResponse = {}
        if errors:
            #failed ver
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors
        else:
            #pass
            hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name = postData['first_name'], userName =
            postData['userName'], password = hashed_password)
            modelsResponse['isRegistered'] = True
            modelsResponse['user'] = user
        return modelsResponse
    def login_user(self, postData):
        user = self.filter(userName = postData['userName'])
        errors = []
        modelsResponse = {}
        if not user:
            errors.append('Invalid userName!')
        else:
            if bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()):
                modelsResponse['isLoggedIn'] = True
                modelsResponse['user'] = user[0]
            else:
                errors.append('Invalid userName/password combination!')
        if errors:
            modelsResponse['isLoggedIn'] = False
            modelsResponse['errors'] = errors
        return modelsResponse
class AuthManager(models.Manager):
    def add_author(self, postData):
        errors = []
        modelsResponse = {}
        if not len(postData['authorList']):
            errors.append('Item is required')
        if len(postData['authorList']) < 3:
            errors.append('Item must be at 3 characters long!')
        if errors:
            #failed ver
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors
        else:
            modelsResponse['isRegistered'] = True
            author = self.create(author = postData['authorList'])
            modelsResponse['author'] = author
        return modelsResponse

class User(models.Model):
    first_name = models.CharField(max_length=50)
    userName = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
class Author(models.Model):
    author = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AuthManager()

apps/wishlist/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/books/views.py
from django.shortcuts import render

# Create your views here.

apps/loginReg/views.py
from django.shortcuts import render, redirect
from .models import User, Author
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'loginReg/index.html')
def addBook(request):
    viewsAuthor = Author.objects.add_author(request.POST)
    if viewsAuthor['isRegistered']:
        request.session['authorList'] = viewsAuthor['author'].author
        return redirect('users:dashboard')
    else:
        for error in viewsAuthor['errors']:
            messages.error(request, error)
    print request.session['authorList']
    return render(request, 'wishlist/index.html')
def register(request):
    viewsResponse = User.objects.add_user(request.POST)
    if viewsResponse['isRegistered']:
        request.session['user_id'] = viewsResponse['user'].id
        request.session['user_fname'] = viewsResponse['user'].first_name
        return redirect('users:dashboard')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('users:index')
def dashboard(request):
    context = {
        'all_courses': Author.objects.all()
    }
    return render(request, 'loginReg/dashboard.html', context)
def add(request):
    return render(request, 'wishlist/index.html')
def login(request):
    viewsResponse = User.objects.login_user(request.POST)
    if viewsResponse['isLoggedIn']:
        request.session['user_id'] = viewsResponse['user'].id
        request.session['user_fname'] = viewsResponse['user'].first_name
        return redirect('users:dashboard')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('users:index')
def logout(request):
    request.session.clear()
    return redirect('users:index')
def delete(request, author_id):
    # pseudo
    # if clicked while logged in:
    #     then add to other's wish list and delete from your wishlist
    Author.objects.get(id = author_id).delete()
    return redirect('users:dashboard')
def wish_items(request, author_id):
    context = {
        'course': Author.objects.get(id=author_id),
    }

    return render(request, 'wishlist/wish_list.html', context)

apps/wishlist/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'wishlist/index.html')

apps/books/templates/books/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    books
  </body>
</html>

apps/loginReg/templates/loginReg/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Page</title>
  </head>
  <style>
    #title{
      float: right;
      display: inline-block;
    }
    #title form{
      display: inline-block;
    }
    #leftMargin{
      margin-left: 35px;
    }
    #subButton{
      position: relative;
      left: 470px;
    }
  </style>
  <body>
    <div id="wrapper">
      <div id="title">
        <form class="" action="{% url 'users:dashboard' %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="Home">
        </form>
        <form class="" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="Logout">
        </form>
      </div>
      <h2>Add a New Book Title and a Review</h2>
      <form class="" action="{% url 'users:addBook' %}" method="post">
        {% csrf_token %}
        <p><label>Book Title: </label><input type="text" name="bookTitle"></p>
        <p>Author:</p>
        <div id="leftMargin">
          <p>Choose from the list:

          </p>
          <p>Or add a new author:
            <input type="text" name="authorList" value="dfd">
          </p>
          <p>Review:</p>
          <p> <textarea name="comment" rows="8" cols="80"></textarea></p>
          Rating: <select class="" name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select> stars
        </div>
        <div id='subButton'>
          <input type="submit" name="" value="Add Book and Review">
        </div>
      </form>
    </div>
  </body>
</html>

apps/loginReg/templates/loginReg/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome Page</title>
  </head>
  <style>
    #header{
      display: inline-block;
    }
    .links{
      display: inline-block;
      /*vertical-align: top;*/
    }
    .right{
      float: right;

    }
    #wrapper{
      width: 800px;

    }


  </style>
  <body>
    <div id="wrapper">
      <div class="links">
        <h2>Welcome, {{ request.session.user_fname }}!</h2>
      </div>
      <div class ="links, right">
        <form class="" action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <input type="submit" name="" value="Logout">
        </form>
      </div>
      <div id="leftMain">
        <h3>Your Wish List</h3>
        <table border = 1>
          <thead>
            <tr>
              <td>Item</td>
              <td>Added by</td>
              <td>Date Added</td>
              <td>Actions</td>
            </tr>
          </thead>
          <tbody>
              {% for wish in all_courses %}
                <tr>
                  <td><a href="wish_items/{{wish.id}}">{{wish.author }}</a></td>
                  <td>{{ request.session.user_fname }}</td>
                  <td>{{ wish.created_at }}</td>
                  <td><a href="delete/{{wish.id}}">Remove</a></td>
                </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
      <div id="rightMain">
        <h3>Other User's Wish List</h3>

      </div>
      <div class ="links, right">
        <form class="" action="{% url 'users:add' %}" method="post">
          {% csrf_token %}
          <input type="submit" name="" value="Add Item">
        </form>
      </div>
    </div>
  </body>
</html>

apps/loginReg/templates/loginReg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login/ Registration</title>
  </head>
  <style>
  .register{
    display: inline-block;
    border: 1px solid black;
    padding: 15px;

  }
  .login {
    display: inline-block;
    vertical-align: top;
    border: 1px solid black;
    padding: 15px;
  }
  form {
    display: table;
  }
  p {
    display: table-row;
  }
  label {
    display: table-cell;
  }
  input {
    margin-left: 5px;
    display: table-cell;
  }
  #sub {
    position: relative;
    left: 360px;
    top: 10px;
  }
  #sub2{
    position: relative;
    left: 178px;
    top: 10px;
  }
  h3{
    margin: 0px;
    margin-bottom: 10px;
    text-decoration: underline;
  }
  </style>
  <body>
    <h1>Welcome</h1>
    <div class="register">
      {% if messages %}
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <h3>Registration</h3>
      <form class="" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <p><label>Name: </label><input type="text" name="first_name" value=""></p>
        <p><label>Username: </label><input type="text" name="userName" value=""></p>
        <p><label>Password: </label><input type="password" name="password" value=""></p>
        <p>*Password should be at least 8 characters</p>
        <p><label>Confirm PW: </label><input type="password" name="confirm_password" value=""></p>
        <p><label>Date Hired: </label><input type="datehired" name="datehired" value=""></p>
        <input id = "sub" type="submit" name="" value="Register">
      </form>
    </div>
    <div class="login">
      <h3>Login</h3>
      <form class="" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <p><label>Username: </label><input type="userName" name="userName" value=""></p>
        <p><label>Password: </label><input type="password" name="password" value=""></p>
        <input id = "sub2" type="submit" name="" value="Login">
      </form>
    </div>
  </body>
</html>

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Page</title>
  </head>
  <style>
    #title{
      float: right;
      display: inline-block;
    }
    #title form{
      display: inline-block;
    }
    #wrapper{
      width: 800px;
    }
  </style>
  <body>
    <div id="wrapper">
      <div id="title">
        <form class="" action="{% url 'users:dashboard' %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="Home">
        </form>
        <form class="" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="Logout">
        </form>
      </div>
      {% if messages %}
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <h2>Create a New Wish List Item</h2>
      <form class="" action="{% url 'users:addBook' %}" method="post">
        {% csrf_token %}
        <p>Item/Product:<input type="text" name="authorList"></p>
        <input type="submit" name="" value="Add">
      </form>
    </body>
</html>

apps/wishlist/templates/wishlist/wish_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Delete this</title>
  </head>
  <body>
  <style>
    #title{
      float: right;
      display: inline-block;
    }
    #title form{
      display: inline-block;
    }
    .wrapper{
      width: 850px;
    }
    </style>
    <div class="wrapper">
      <div id="title">
        <form class="" action="{% url 'users:dashboard' %}" method="post">
        {% csrf_token %}
          <input type="submit"  value="Home">
        </form>
        <form class="" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
          <input type="submit" value="Logout">
        </form>
      </div>
      <h1>{{ course.author }}</h1>
      <p>Users who added this product/item under their wish list:</p>
    <!-- pseudo for loop that loops thru author_id(many to many relationship with user and item) -->
    </div>

  </body>
</html>